      tailwind.config = {
          darkMode: "class",
          theme: {
            extend: {
              "colors": {
                      "background": "#faf8ff",
                      "on-primary": "#ffffff",
                      "tertiary-container": "#9b6500",
                      "on-secondary": "#ffffff",
                      "primary": "#593bce",
                      "secondary-container": "#e0ddf5",
                      "inverse-primary": "#cabeff",
                      "surface-dim": "#dad9e1",
                      "on-primary-fixed-variant": "#4723bc",
                      "on-secondary-container": "#626075",
                      "tertiary-fixed-dim": "#ffb955",
                      "surface": "#faf8ff",
                      "error": "#ba1a1a",
                      "surface-container-highest": "#e2e2e9",
                      "surface-tint": "#6043d5",
                      "on-background": "#1a1b21",
                      "primary-container": "#7257e8",
                      "secondary-fixed-dim": "#c7c4db",
                      "surface-container": "#eeedf5",
                      "on-error-container": "#93000a",
                      "surface-bright": "#faf8ff",
                      "on-secondary-fixed-variant": "#464558",
                      "outline": "#797586",
                      "on-error": "#ffffff",
                      "surface-container-low": "#f4f3fb",
                      "primary-fixed": "#e6deff",
                      "outline-variant": "#c9c4d7",
                      "on-primary-fixed": "#1c0062",
                      "surface-container-high": "#e8e7ef",
                      "secondary": "#5e5c70",
                      "surface-variant": "#e2e2e9",
                      "on-tertiary-fixed": "#291800",
                      "on-tertiary": "#ffffff",
                      "on-primary-container": "#f9f3ff",
                      "on-tertiary-container": "#fff4ea",
                      "secondary-fixed": "#e3e0f8",
                      "inverse-surface": "#2f3036",
                      "error-container": "#ffdad6",
                      "on-surface": "#1a1b21",
                      "tertiary-fixed": "#ffddb4",
                      "tertiary": "#7a4f00",
                      "on-tertiary-fixed-variant": "#633f00",
                      "inverse-on-surface": "#f1f0f8",
                      "on-secondary-fixed": "#1a1a2b",
                      "primary-fixed-dim": "#cabeff",
                      "on-surface-variant": "#484554",
                      "surface-container-lowest": "#ffffff"
              },
              "borderRadius": {
                      "DEFAULT": "0.25rem",
                      "lg": "0.5rem",
                      "xl": "0.75rem",
                      "full": "9999px"
              },
              "spacing": {
                      "container-margin": "32px",
                      "gutter": "24px",
                      "md": "24px",
                      "xl": "64px",
                      "xs": "4px",
                      "sm": "12px",
                      "base": "8px",
                      "lg": "40px"
              },
              "fontFamily": {
                      "body-lg": ["Inter"],
                      "body-md": ["Inter"],
                      "headline-lg": ["Inter"],
                      "label-md": ["Inter"],
                      "label-sm": ["Inter"],
                      "headline-sm": ["Inter"],
                      "body-sm": ["Inter"],
                      "headline-md": ["Inter"],
                      "headline-lg-mobile": ["Inter"],
                      "display-lg": ["Inter"]
              },
              "fontSize": {
                      "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                      "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
                      "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
                      "label-md": ["14px", {"lineHeight": "1.2", "fontWeight": "600"}],
                      "label-sm": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "500"}],
                      "headline-sm": ["20px", {"lineHeight": "1.4", "fontWeight": "600"}],
                      "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
                      "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
                      "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "700"}],
                      "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}]
              }
            }
          }
        }