     tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "on-error-container": "#93000a",
                        "secondary": "#5e5c70",
                        "on-secondary-fixed": "#1a1a2b",
                        "surface-container": "#eeedf5",
                        "on-background": "#1a1b21",
                        "secondary-container": "#e0ddf5",
                        "surface-container-high": "#e8e7ef",
                        "primary-container": "#7257e8",
                        "on-primary-fixed": "#1c0062",
                        "surface": "#faf8ff",
                        "on-secondary-container": "#626075",
                        "on-primary": "#ffffff",
                        "on-primary-container": "#f9f3ff",
                        "primary": "#593bce",
                        "inverse-on-surface": "#f1f0f8",
                        "inverse-surface": "#2f3036",
                        "outline-variant": "#c9c4d7",
                        "on-tertiary": "#ffffff",
                        "surface-container-lowest": "#ffffff",
                        "primary-fixed": "#e6deff",
                        "secondary-fixed-dim": "#c7c4db",
                        "secondary-fixed": "#e3e0f8",
                        "surface-container-highest": "#e2e2e9",
                        "tertiary-container": "#9b6500",
                        "on-surface": "#1a1b21",
                        "surface-container-low": "#f4f3fb",
                        "tertiary-fixed": "#ffddb4",
                        "inverse-primary": "#cabeff",
                        "surface-tint": "#6043d5",
                        "on-tertiary-fixed": "#291800",
                        "tertiary-fixed-dim": "#ffb955",
                        "on-tertiary-container": "#fff4ea",
                        "error": "#ba1a1a",
                        "tertiary": "#7a4f00",
                        "outline": "#797586",
                        "on-surface-variant": "#484554",
                        "surface-dim": "#dad9e1",
                        "surface-bright": "#faf8ff",
                        "background": "#faf8ff",
                        "on-secondary-fixed-variant": "#464558",
                        "primary-fixed-dim": "#cabeff",
                        "on-error": "#ffffff",
                        "surface-variant": "#e2e2e9",
                        "on-secondary": "#ffffff",
                        "on-tertiary-fixed-variant": "#633f00",
                        "error-container": "#ffdad6",
                        "on-primary-fixed-variant": "#4723bc"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.25rem",
                        "lg": "0.5rem",
                        "xl": "0.75rem",
                        "full": "9999px"
                    },
                    "spacing": {
                        "xl": "64px",
                        "container-margin": "32px",
                        "sm": "12px",
                        "md": "24px",
                        "xs": "4px",
                        "lg": "40px",
                        "base": "8px",
                        "gutter": "24px"
                    },
                    "fontFamily": {
                        "headline-lg-mobile": ["Inter"],
                        "headline-lg": ["Inter"],
                        "label-sm": ["Inter"],
                        "body-md": ["Inter"],
                        "body-lg": ["Inter"],
                        "headline-md": ["Inter"],
                        "headline-sm": ["Inter"],
                        "display-lg": ["Inter"],
                        "body-sm": ["Inter"],
                        "label-md": ["Inter"]
                    },
                    "fontSize": {
                        "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "700" }],
                        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
                        "label-sm": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "500" }],
                        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
                        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
                        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
                        "headline-sm": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
                        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
                        "label-md": ["14px", { "lineHeight": "1.2", "fontWeight": "600" }]
                    }
                }
            }
        }